parameters:
#    ws_style.example.class: Ws\StyleBundle\Example

services:
#    ws_style.example:
#        class: %ws_style.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]