# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    #ROLES
    role_hierarchy:
        ROLE_ADMIN:       
            - ROLE_USER
            - ROLE_WORLD_ADMIN
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN: 
            - ROLE_USER         
            - ROLE_ADMIN
            - ROLE_WORLD_ADMIN
            - ROLE_SONATA_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    encoders:
        #Password Encoder
        FOS\UserBundle\Model\UserInterface: { id: user.password_encoder }
        
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true

            form_login:
                provider: fos_userbundle
                check_path: fos_user_security_check
                login_path:  fos_user_security_login
                use_referer: true
                default_target_path: world_index
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
