#user_delete_me:
#    pattern: /profile/delete/{template}
#    defaults: { _controller: ZogsUserBundle:User:delete, template: 'delete' }
#
#user_request_activation_mail:
#    pattern: /activation/me
#    defaults: { _controller: ZogsUserBundle:User:requestActivationMail }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

#user_login_checker:
#    pattern: /check/username
#    defaults: { _controller: ZogsUserBundle:User:checkUsername }

#user_email_checker:
#    pattern: /check/email
#    defaults: { _controller: ZogsUserBundle:User:checkEmail }

#user_profil_view:
#    pattern: /user/{id}/{username}
#    defaults: { _controller: ZogsUserBundle:User:viewProfil }
#    requirements:
#        id: \d+


#admin
admin_user_index: # useful??
    path: /admin/user/index
    defaults: { _controller: ZogsUserBundle:Admin:index }
user_admin_switch_to_user:
    path: /admin/user/switch_to/{user}
    defaults: { _controller: ZogsUserBundle:Admin:switchToUser }
    requirements:
        user: \d+