<?php

namespace AppBundle\Entity;

/**
 * AppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppRepository extends \Doctrine\ORM\EntityRepository
{
}
